// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4cidzUMlQFhg7KcT-xAVbnGwCBYAJ9FE',
    appId: '1:434832672873:web:ecf45956c104109320baf8',
    messagingSenderId: '434832672873',
    projectId: 'repuestos-24-7',
    authDomain: 'repuestos-24-7.firebaseapp.com',
    storageBucket: 'repuestos-24-7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNa7H_pzgpB2TjbTjqCdVkoUwxRGKPdNw',
    appId: '1:434832672873:android:b84ef504f7d3d68920baf8',
    messagingSenderId: '434832672873',
    projectId: 'repuestos-24-7',
    storageBucket: 'repuestos-24-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1e7HzvsmM4O8PVqsAaY2h1LP-IHw8hIA',
    appId: '1:434832672873:ios:cb40f076654b77ad20baf8',
    messagingSenderId: '434832672873',
    projectId: 'repuestos-24-7',
    storageBucket: 'repuestos-24-7.firebasestorage.app',
    iosBundleId: 'com.dev.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1e7HzvsmM4O8PVqsAaY2h1LP-IHw8hIA',
    appId: '1:434832672873:ios:cb40f076654b77ad20baf8',
    messagingSenderId: '434832672873',
    projectId: 'repuestos-24-7',
    storageBucket: 'repuestos-24-7.firebasestorage.app',
    iosBundleId: 'com.dev.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4cidzUMlQFhg7KcT-xAVbnGwCBYAJ9FE',
    appId: '1:434832672873:web:0327b00e8ab59e4c20baf8',
    messagingSenderId: '434832672873',
    projectId: 'repuestos-24-7',
    authDomain: 'repuestos-24-7.firebaseapp.com',
    storageBucket: 'repuestos-24-7.firebasestorage.app',
  );

}